### ISSUE TITLE
Unable to find model file

### ISSUE THREAD

**Issue by MudasserAfzal** [sshh12/Conv-VAD#1]
When I run the setup.py file it instead of creating the model file and the directories as you mentioned in the setup.py file it produces .egg file which I didn't understand. can you help me out?

**Comment by sshh12** [comment]
Sorry for the late reply. If you're still interested in figuring this out, could you describe what you're trying to do? What commands? and what's being logged?

**Comment by v-nhandt21** [comment]
![image](https://user-images.githubusercontent.com/36092323/199684038-d0536c06-03bb-4e71-beec-06cd51a19693.png)

When I run python demo.py, It can not find the H5 file

Could you share the model checkpoint?

Update: The checkpoint in this releases: https://github.com/sshh12/Conv-VAD/releases

Thank you
